{{- if and .Values.statefulset.enabled .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-python.headlessServiceName" . }}
  labels:
    {{- include "devops-python.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "devops-python.selectorLabels" . | nindent 4 }}
{{- end }}
