{{- if .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "devops-python.fullname" . }}
  labels:
    {{- include "devops-python.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "devops-python.headlessServiceName" . }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: {{ .Values.statefulset.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.statefulset.updateStrategy.type }}
    {{- if and (eq .Values.statefulset.updateStrategy.type "RollingUpdate") .Values.statefulset.updateStrategy.rollingUpdate }}
    rollingUpdate:
      partition: {{ .Values.statefulset.updateStrategy.rollingUpdate.partition }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "devops-python.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devops-python.selectorLabels" . | nindent 8 }}
      {{- if .Values.config.enabled }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "devops-python.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount | default false }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if or .Values.config.enabled .Values.secrets.enabled }}
          envFrom:
            {{- if .Values.config.enabled }}
            - configMapRef:
                name: {{ include "devops-python.configEnvName" . }}
            {{- end }}
            {{- if .Values.secrets.enabled }}
            - secretRef:
                name: {{ include "devops-python.secretName" . }}
            {{- end }}
          {{- end }}
          env:
            {{- include "devops-python.envVars" . | nindent 12 }}
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.config.enabled }}
            - name: config-volume
              mountPath: {{ .Values.config.mountPath | quote }}
              readOnly: true
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: data-volume
              mountPath: {{ .Values.persistence.mountPath | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml $.Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $.Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- if .Values.config.enabled }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "devops-python.configFileName" . }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data-volume
        labels:
          {{- include "devops-python.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
  {{- end }}
{{- end }}
