# Server Configuration
server.port=8080

# Application Configuration
app.version=1.0.0

# Logging
logging.level.root=INFO
logging.level.com.devops.info=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n

# Actuator
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
